# Generated by Django 2.0.6 on 2018-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_in_car', models.CharField(choices=[('AU', 'AUDI'), ('BW', 'BMW'), ('HD', 'Honda'), ('NS', 'Nissan')], default=None, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(max_length=6, unique=True)),
            ],
        ),
    ]
